name: at_contact
description: A starting point for Dart libraries or applications.
version: 1.0.0+4
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  at_client: ^1.0.1+9
  at_commons: ^1.0.1+7
  at_utils: ^1.0.1+7
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
