# This workflows runs when
# 1. pull_request raised to trunk branch.
# 2. tag created on at_tools repository
name: at_libraries

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # Install dependencies in at_contacts library
      - name: Install dependencies in at_contact
        working-directory: at_contact
        run: dart pub get

      # Run analyzer in at_contacts library
      - name: Analyze project source in at_contact
        working-directory: at_contact
        run: dart analyze

      # Install dependencies in at_lookup library
      - name: Install dependencies in at_lookup
        working-directory: at_lookup
        run: dart pub get

      # Run dart analyzer in at_lookup library
      - name: Analyze project source in at_lookup
        working-directory: at_lookup
        run: dart analyze

      # Install dependencies in at_server_status status
      - name: Install dependencies in at_server_status library
        working-directory: at_server_status
        run: dart pub get

      # Run dart analyzer in at_server_status library
      - name: Analyze project source in at_server_status library
        working-directory: at_server_status
        run: dart analyze
